apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: minecraft
  namespace: minecraft

spec:
  serviceName: minecraft

  replicas: 1

  selector:
    matchLabels:
      app: minecraft

  template:
    metadata:
      labels:
        app: minecraft

    spec:
      containers:
        - name: minecraft

          image: 619786279459.dkr.ecr.us-east-1.amazonaws.com/minecraft-server:v1

          ports:
            - containerPort: 25565

          envFrom:
            - configMapRef:
                name: minecraft-config

          volumeMounts:
            - name: minecraft-storage
              mountPath: /data

          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 120
            periodSeconds: 30

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"

            limits:
              memory: "4Gi"
              cpu: "2"

      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-data